x-logging: &default-logging
  driver: json-file
  options:
    max-size: "1m"
    max-file: "1"

x-health-defaults: &health-defaults
  interval: 1m
  timeout: 15s
  retries: 5
  start_period: 5m
  start_interval: 5s

services:

  db:
    container_name: db-26ai-free
    image: container-registry.oracle.com/database/free:latest
    restart: unless-stopped
    logging: *default-logging
    environment:
      - ORACLE_PWD=${ORACLE_PWD}
      - ENABLE_ARCHIVELOG=${ENABLE_ARCHIVELOG:-FALSE}
      - ENABLE_FORCE_LOGGING=${ENABLE_FORCE_LOGGING:-FALSE}
    ports:
      - 127.0.0.1:${HOST_DB_PORT:-1521}:1521/tcp
    volumes:
      - ./oradata:/opt/oracle/oradata
      - ./db-startup:/opt/oracle/scripts/startup:ro

  ords:
    container_name: ords-node-1
    image: container-registry.oracle.com/database/ords:latest
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      test: [ "CMD-SHELL", "curl -k -f http://localhost:8080/ords/_/landing || exit 1" ]
      <<: *health-defaults
    environment:
      - DEBUG=${DEBUG:-}
      - ORACLE_PWD=${ORACLE_PWD}
      - DBHOST=${DBHOST:-db-26ai-free}
      - DBPORT=${DBPORT:-1521}
      - DBSERVICENAME=${DBSERVICENAME:-FREEPDB1}
      - APEX_ADMIN_USER_NAME=${APEX_ADMIN_USER_NAME:-}
      - APEX_ADMIN_USER_PWD=${APEX_ADMIN_USER_PWD:-}
      - APEX_ADMIN_USER_EMAIL=${APEX_ADMIN_USER_EMAIL:-}
      - OLLAMA_PULL_MODELS=${OLLAMA_PULL_MODELS:-}
    ports:
      - 127.0.0.1:${HOST_ORDS_PORT:-8181}:8080/tcp
    volumes:
      - ./apex:/opt/oracle/apex
      - ./ords-config:/etc/ords/config
      - ./ords-entrypoint.d:/ords-entrypoint.d:ro
      - ./apex_workspaces.yaml:/home/oracle/apex_workspaces.yaml:ro
      - ./apex_instance_parameters.yaml:/home/oracle/apex_instance_parameters.yaml:ro
    depends_on:
      db:
        condition: service_healthy
